### ISSUE TITLE
The command '/bin/sh -c ./postBuild' returned a non-zero code: 127

### ISSUE THREAD

**Issue by rgaiacs** [schochastics/MH_netVizR#2]
I think that https://github.com/schochastics/MH_netVizR/blob/7ce2179e0b82187c270cf8a044e3b4e49507c7a3/postBuild#L1 might be the problem. Can we try https://github.com/gesistsa/rtoot/blob/b804da6620c28f83edddacf0e63f312dfd7bf90b/postBuild#L1 and see it it works at https://mybinder.org/?

**Comment by rgaiacs** [comment]
When I try locally with `repo2docker`, the error is

```
Step 67/72 : RUN ./postBuild
 ---> Running in 333a5c1b85f6
/usr/bin/env: ‘bash -v’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

**Comment by rgaiacs** [comment]
I confirm that the proposed change fixes the issue.

**Comment by schochastics** [comment]
THanks! I will adjust this in https://github.com/gesistsa/usemh. The postBuild is actually created via `quarto use binder` so is this a bug in quarto too?

**Comment by rgaiacs** [comment]
@schochastics I open https://github.com/gesistsa/usemh/issues/11 to keep track of this.
